services:
  brilliantwear-backend:
    image: cscphilip/brilliantwear-backend:latest
    ports: 
      - "7000:7000"
    extra_hosts:
      - "mongoservice:172.17.0.1"
    deploy:
      replicas: 3
    networks:
      - mongo-network

networks:
  mongo-network:
    external: true
