apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: brilliantwear-fullstack-next-pvc
spec:
  storageClassName: brilliantwear-fullstack-next-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
