version: '3.3'

services:
  mongo:
    image: mongo:latest
    volumes:
      - /var/lib/mongodb-docker:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=philip
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongo-root-pw
    secrets:
      - mongo-root-pw
    networks:
      - mongo-network
    logging:
      options:
        max-size: 1g
    ports:
      - "27017:27017"

  mongo-backup:
    image: cscphilip/mongo-backup
    volumes:
      - /var/backups/mongodb:/app/dump
    secrets:
      - mongo-root-pw
    networks:
      - mongo-network
    deploy:
      restart_policy:
        delay: 168h #One week
    depends_on:
      - mongo

secrets:
  mongo-root-pw:
    external: true

networks:
  mongo-network:
    external: true
